import type { MetadataRoute } from "next";

import { env } from "@/lib/env";

/**
 * The web app manifest.
 *
 * Two audiences read this file. A student who taps "Add to home screen" in
 * Chrome gets an installed PWA from it, and Bubblewrap reads it when it
 * generates the Play Store package — the name, colours and icons in the
 * listing all come from here, so this is the single place they're defined.
 *
 * Icons are generated by `node scripts/generate-icons.mjs` from the same glyph
 * and brand token as `src/components/logo.tsx`.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${env.appName} — classes with instructors who actually teach`,
    short_name: env.appName,
    description:
      "Book live and in-person classes with yoga teachers, musicians, dancers and coaches. Schedules, passes, recordings and live classes in one place.",

    // Signed-in students land on their dashboard from here; everyone else is
    // redirected to the marketing page, so "/" is the honest entry point.
    start_url: "/",
    // Everything the app does lives under the origin root. Narrowing this
    // would push in-app links (Razorpay's hosted checkout, for one) out into
    // the browser, which breaks the installed feel.
    scope: "/",
    id: "/",

    display: "standalone",
    orientation: "portrait",

    // Matches `body { background: var(--color-paper) }` so the splash screen
    // doesn't flash white before the first paint.
    background_color: "#fbfaf7",
    // --color-brand-600, the same value as the `theme-color` meta tag in the
    // root layout. Android tints the status bar and the task switcher with it.
    theme_color: "#1f6650",

    lang: "en-IN",
    dir: "ltr",
    categories: ["education", "fitness", "lifestyle"],

    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Android masks these to whatever shape the launcher uses, so the glyph
      // is drawn inside the centre 80% safe zone.
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      // Themed icons on Android 13+: only the alpha channel matters, the
      // launcher supplies the colour.
      {
        src: "/icons/icon-monochrome-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "monochrome",
      },
    ],

    // Long-press the installed icon to jump straight to the two screens people
    // actually open the app for.
    shortcuts: [
      {
        name: "My classes",
        short_name: "Classes",
        url: "/dashboard/bookings",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Find an instructor",
        short_name: "Instructors",
        url: "/instructors",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
    ],

    // Chrome will offer the Play listing instead of a browser install once the
    // app is published, but only if the package name is configured.
    ...(env.android.packageName
      ? {
          related_applications: [
            {
              platform: "play",
              id: env.android.packageName,
              url: `https://play.google.com/store/apps/details?id=${env.android.packageName}`,
            },
          ],
          prefer_related_applications: true,
        }
      : {}),
  };
}
